name: edash
channels:
  - conda-forge
dependencies:
  - h5netcdf
  - panel
  - numpy
  - xarray
  - pooch
  - holoviews
  - hvplot
  - geopandas
  - geoviews
  - matplotlib
  - rasterio
  - rioxarray
  - shapely
  - gdown
  - jupyter-server-proxy
  - nodejs
  - pip
  - pip:
    - opencv-python-headless
    - "git+https://github.com/GlacioHack/xdem.git#egg=xdem"
    - "git+https://github.com/GlacioHack/GeoUtils.git#egg=GeoUtils"
