name: edash
channels:
  - conda-forge
dependencies:
  - black
  - geopandas
  - geoviews
  - holoviews
  - hvplot
  - matplotlib
  - numpy
  - panel
  - rasterio
  - rioxarray
  - shapely
  - xarray
  - pip
   - pip:
    - "git+https://github.com/GlacioHack/xdem.git#egg=xdem"
    - "git+https://github.com/GlacioHack/GeoUtils.git#egg=GeoUtils"